### PR TITLE
Improve sponsors page

### PR DESCRIPTION
**Pull request by lboynton**
- Add Magma Digital and Buffalo to sponsors
- Improve design a bit

sponsors

Let me know what you think of the design!

### CODE REVIEW

**Comment by asgrim** [comment]
Yeah - that looks much nicer! Is it easy enough to stop the text from wrapping around the Magma logo (i.e. just have the logo on the left, and a single column of text)

**Comment by lboynton** [comment]
Should be, I can take a look later today

**Comment by asgrim** [comment]
Thanks!

**Comment by rossey** [comment]
Could we pop a placeholder Where you've got available, might look better next to the other logos?

**Comment by lboynton** [comment]
@rossey Yeah I agree that would look better, anyone have a placeholder we can use?

**Comment by lboynton** [comment]
Moved the Magma Digital logo to a separate column. I actually think it looked better before.

sponsors2

**Comment by asgrim** [comment]
Hmm, maybe put the text below the logo? Can make the logo bigger then :) I don't have a placeholder, maybe just a question mark?

**Comment by lboynton** [comment]
sponsors3

**Comment by asgrim** [comment]
Yeeah that looks better I reckon :)

**Comment by lboynton** [comment]
Added TBC placeholders

sponsors4

**Comment by lboynton** [comment]
sponsors-mobile

**Comment by asgrim** [comment]
Cool, I'll merge this then we can make any further improvements later :)

**Pull request merged**
