### PR TITLE
Set canonical URL to 2016 (thanks @tacoverdo!)

### PR DESCRIPTION
**Pull request by asgrim**
Apparently this should help 2015 site appearing first on Google now :) credit to @tacoverdo of @yoast for the advise here :)

### CODE REVIEW

**Comment by lboynton** [comment]
Do we want every page on the site to have the same canonical URL though? Or do we want each page just to point to the 2016 subdomain instead, with different paths?

**Comment by asgrim** [comment]
@lboynton I'm not sure how to do that with the Jekyll template :P

**Comment by lboynton** [comment]
:unamused:

**Comment by lboynton** [comment]
I've changed it so that http://2015.phpsouthcoast.co.uk/sponsors/ now has a canonical URL of http://2016.phpsouthcoast.co.uk/sponsors/

I still don't know if this is right though? Will this mean people can't find the 2015 version via search engines?

**Comment by asgrim** [comment]
@lboynton that's acceptable imo; it's not a far fetch to change the year in the address bar

**Comment by asgrim** [comment]
@lboynton doesn't this mean every page on 2015 needs a corresponding page on 2016 though?

**Comment by lboynton** [comment]
Yes it does, which is the case except for the info page.

**Pull request merged**
