### PR TITLE
Fixed nav

### PR DESCRIPTION
**Pull request by dashaluna**
@asgrim @lboynton 
- [x] Made header fixed
- [x] Added "Buy Ticket" button to the far right in the header

Can we deploy that to test and have a look before putting it on live? :)

### CODE REVIEW

**Comment by asgrim** [comment]
A few issues I spotted - on smaller screens, the logo is covered by the menu:

coverlogo
coverlogo2

And on some pages, the fixed header now means some content is pushed up "underneath" (so needs some top padding or margin or something?):

no-padding
top-spacing

**Comment by asgrim** [comment]
It's on the staging domain now: http://staging.2015.phpsouthcoast.co.uk/

**Comment by lboynton** [comment]
I guess we need to collapse the menu a bit earlier, as the screen width gets smaller. I think it's better with the fixed header, and the buy ticket button is certainly more prominent now.

**Comment by asgrim** [comment]
Yep - otherwise looks ossum & much easier to buy tickets! That's the aim of the game

**Comment by dashaluna** [comment]
@asgrim thanks will have a look into it further

**Comment by dashaluna** [comment]
@asgrim I've cleaned up most of the things, except the menu covering up the logo on smaller screens. @lboynton do we have a CSS for iPad size screens? I wonder if we can trim margin between the menu links and make the logo slightly smaller instead of collapsing menu for iPad. What do you guys think?

**Comment by lboynton** [comment]
@dashaluna I think style-narrow.css is for tablet sized screens. I agree the logo could definitely be made smaller there, that would allow the buttons to remain visible.

**Comment by dashaluna** [comment]
@lboynton this should be fixed now, have a look at normal/tablet/mobile views. Let me know what you think

**Comment by asgrim** [comment]
@dashaluna hmm, at the size just above mobile, the logo gets squished?
squish

Also some overlap ~1092 width:

**Comment by dashaluna** [comment]
Ah :( I'm not front-end expert... @lboynton would you mind having a look at it please? If not, I can ask Jenny maybe?

**Comment by lboynton** [comment]
Sure, I'll try to have a look tonight.

**Comment by lboynton** [comment]
How about that? I've reduced the padding and margin on the nav links to prevent the buttons overlapping the logo.

header-logo-1081px

**Comment by asgrim** [comment]
Pretty much there - slight overlap on the T on the larger size, but I'm done with this, I'm putting it live :)

Thanks loads @lboynton & @dashaluna - awesome stuff!

**Pull request merged**
