### PR TITLE
[WIP] Schedule page

### PR DESCRIPTION
**Pull request by lboynton**
Just an initial attempt at the schedule page. Please give any feedback!

TODO:
- [x] make the time column narrow
- [x] fixed width column sizes (currently track 2 column is smaller width than track 1)
- [x] use track names

phpsc-schedule

### CODE REVIEW

**Comment by asgrim** [comment]
Maybe alternate the talk colours? I'm not a designers, so I don't really know :)

**Comment by asgrim** [comment]
I think the "time" column just needs to be as thin as possible - some of the talk names can be quite long, so want to make sure the've got enough room. I think for the talk box content it should be:

``` html
<strong>Keynote: Speaker Name</strong>
<p>This is the talk title</p>
```

or whatever the HTML is these days, without the "Keynote: " bit for the other talks

**Comment by asgrim** [comment]
oh also track names are:
Track 1 => Spectrum IT Room
Track 2 => Magma Digital Room

**Comment by asgrim** [comment]
Also, for reference, this WIP branch is currently on http://staging.2015.phpsouthcoast.co.uk/schedule/

**Comment by rossey** [comment]
Could we split the tracks up by tabs or similar? I like the timeline idea that Chris designed for the redevelop conference http://redevelop.io/schedule *note I know we're not redevelop, but we don't have a designer ;)

**Comment by lboynton** [comment]
Yep that looks really nice! The issue is the talks being on at different
times in track 1 and 2, we could have a timeline that branches off for the
different tracks maybe? Or have two timelines?

What do you mean by tabs?

**Comment by asgrim** [comment]
Not a bad idea - Then you can separate the time completely. The only thing is you lose the "relativity" between the tracks (i.e. if you attend main talk 1, you will miss both lightning 1+2)

**Comment by rossey** [comment]
yeah that's true. You could fork the timeline or provide two timelines side by side? Or have two single  timelines that you switch between using tabs

**Comment by rossey** [comment]
You could also use one timeline and colour code the different track talks

**Comment by lboynton** [comment]
Made a few more changes. If we want a timeline like redevelop that might take a bit longer (and need a designer maybe).

Happy to try out the tabs idea, but I won't get round to that till Friday/the weekend.

phpsc-schedule2

**Comment by asgrim** [comment]
Cool, :+1:

**Comment by asgrim** [comment]
Added speaker page - I don't see any major problems, but feedback welcome :)

speaker

**Comment by richsage** [comment]
looks nice. what about (when the joind.in event is populated) having somewhere a link across to the relevant talks on joind.in? secondary thing though, it looks good as is now :-)

**Comment by asgrim** [comment]
@richsage good plan! I've added to Trello (https://trello.com/c/5SpPotCi/52-add-links-to-joind-in-talks-for-our-speaker-talks)

**Pull request merged**
