### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by dashaluna**
Nearly there. Needs some responsive tweaking for venue image and info text around it.

### CODE REVIEW

**Comment by dashaluna** [comment]
Might be a good idea to run by Chris (Alex's colleague) to check colours and general look.

**Comment by lboynton** [comment]
Looks good :) I like the responsive menu.

**Comment by dashaluna** [comment]
Apologies about non-Unix line endings I think it's my PHPStorm and I can't figure out how to turn that off.

**Comment by lboynton** [comment]
Ah no worries, it wasn't hard to change (and it probably would've been fine with Windows line endings but Unix tends to work best generally).

**Comment by rossey** [comment]
@dashaluna IIRC I think you can configure git on windows to convert windows => unix line endings and vice versa

**Comment by dashaluna** [comment]
Hmm, that's strange, I never had problems with line endings before. I'm on mac. I did this https://help.github.com/articles/dealing-with-line-endings/ but that doesn't seem to solve the problem :(

**Comment by lboynton** [comment]
OMG! :+1: :relieved: :dancers: :sparkles: :boom: :star: :dizzy_face: :joy_cat:

**Pull request merged**
