### PR TITLE
Add speaker Twitter profiles

### PR DESCRIPTION
**Pull request by lboynton**
Can someone please double check I've got the right Twitter profiles ;)

@phphants/php-south-coast-web-team

### CODE REVIEW

**Comment by lboynton** [comment]
OK to merge?

**Comment by asgrim** [comment]
oops, for some reason this slipped my radar. Reviewing now

**Comment by asgrim** [comment]
Yep they all look right, thanks :)

**Comment by lboynton** [comment]
Cool :)

**Pull request merged**
