### PR TITLE
Added information page

### PR DESCRIPTION
**Pull request by asgrim**
Visible at http://staging.2015.phpsouthcoast.co.uk/information/

### CODE REVIEW

**Comment by davidyell** [comment]
Where is the actual venue? I assumed it was the green star, but that says 'Dockyard entrance'

**Comment by davidyell** [comment]
MIght I recommend colouring Car related items in one colour, and train in another, ferry in another etc. To allow more visual differentiation. Perhaps even a key?

It would be a bit nicer if the map was a bit squarer too, but that's purely personal preference.

I like this page! :+1:

**Comment by asgrim** [comment]
@davidyell they are already grouped by colour (in the map)? :)

The dockyard entrance is where you should head to, and then follow the blue line! I'll try and make that a bit clearer

**Comment by asgrim** [comment]
Updated the map with more info, and also a sticker on the actual venue location :)

**Comment by davidyell** [comment]
> @davidyell they are already grouped by colour (in the map)? :)

D'oh, so they are. I think it was because there are not multiples of the same, except car and ferry, which meant I didn't notice. My mistake.

**Pull request merged**
